#!/bin/bash

CAPS=$(xset -q | grep Caps | sed -E 's/.*Caps Lock:[^a-z]+([a-z]+).*/ \1/')

echo 🔤 #full text
echo 🔤 #short text

if [ $CAPS = 'on' ]; then
    echo \#FFD700 # color
else
    echo \#586e75 # color
fi
